# Generated by Django 3.0.6 on 2020-07-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_weather',
            old_name='city',
            new_name='name',
        ),
    ]
